---
- name: clean_seq
  workflow_path: /Users/dmorais/scratch/python_scripts/AI/bioblend/
  inputs:
    - Test.fastq
  inputs_path: /Users/dmorais/scratch/python_scripts/AI/bioblend/
  inputs_label:
    - fastq
  dbkey:
    - hg19

